site_name: Devbot Documentation
theme: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
nav:
    - Introduction: 'index.md'
    - Adding to Your Server: 'adding-to-your-server.md'
