site_name: Devbot Documentation
theme: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
nav:
    - Introduction: 'index.md'
    - Adding to Your Server: 'adding-to-your-server.md'
    - Custom Commands:
        - Introduction to Custom Commands: 'custom-commands/introduction-to-custom-commands.md'
        - Action Objects: 'custom-commands/action-objects.md'
        - Text Escapes: 'custom-commands/text-escapes.md'
